eureka:
    instance:
        lease-renewal-interval-in-seconds: 2
        lease-expiration-duration-in-seconds: 3
        metadata-map: 
            management.version: 2
    client:
        service-url:
            default-zone:  http://localhost:8761/eureka/
    dashboard: 
        enabled: false
        baseurl: /
management: 
    endpoints: 
        web: 
            exposure: 
                include: '*'