server:
    port: 8761
    servlet: 
        context-path: /
spring:
    application:
        name: eureka
eureka:
    instance:
        hostname: eureka-server
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 2
        lease-expiration-duration-in-seconds: 3
        # ip-address
    client:
        register-with-eureka: true
        service-url:
            default-zone:  http://localhost:${server.port}/eureka/
    server:
        wait-time-in-ms-when-sync-empty: 0
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 5000
